### ISSUE TITLE
OnlyContributor definition

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/contracts#275]
We currently have an interesting usecase where the role of Contributor is based on if an address has a running payment in the streamingPaymentProcessor or not.
In the case of the RecurringPaymentManager Logicmodule we have a possibility that the payments are not triggered for longer periods of time, because no one uses the trigger function, which can lead to the case where someone on the "payroll" who should have the contributor access actually doesnt have it

Its not very critical, because the only place where its used is in the MilestoneManager anyway, but for later implementation this might be something to consider

**Comment by FHieser** [comment]
As it is an Role Problem this might be connected to #276

**Comment by marvinkruse** [comment]
We discussed this, the contributors of the `StreamingPaymentProcessor` are not necessarily the contributors of the `MilestoneManager` or the `RecurringPaymentManager`. So the only thing we need to do here to resolve this confusion would be to rename the "contributor" naming in the `StreamingPaymentProcessor` since the payment receiver(s) don't need to be contributors necessarily.

So we would just rename "contributors" in the `StreamingPaymentProcessor` to "receivers" or "paymentReceivers" or so.
