### ISSUE TITLE
Authorizer update

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/contracts#276]
The team discusses options for a role-based authorizer module. They consider using the Open Zeppelin access control or building their own, more complex version using the Zodiac structure. The team agrees that given their limited resources, it makes sense to go with Open Zeppelin for now and potentially migrate to Zodiac in the future.

Needed for implementation:
-hasRole ideally includes a sub information parameter, an enum for example in case we want to check for specific information (has the address an NFT)

**Comment by 0xNuggan** [comment]
## Design idea for the Role-Based authorizer

To build the RoleAuthorizer around the OZ AccessControl I came across the following issue: It's designed to be inherited and used to manage access control to itself, not really to third parties. I'd like to share the design I came up with to address this, as a way to sanity check with the team :) 

My solution looks like this:
- Each Module internally defines the roles it uses inside an Enum.
- BUT: The RoleAuthorizer (which inherits AccessControl) is the Module that actually stores the addresses that have that role. 
- The roles are stored with an Id like this: `bytes32 role = keccak256(abi.encodepacked( type(/*InterfaceOfTheModule*/, /*EnumValueOfTheRole*/)))`
- Each module can manage the addresses it assignst to its own roles, but the Proposal Owner is set as Role Admin, so there is a second, central way to modify them.
- Also, the Proposal Contract itself defines the roles of "owner" and "manager", and initializes the Authorizer with them.
- All modules can read roles from other modules for their own validation purposes. They just have to import the interface and generate the role identifier when calling the authorizer to check on an address.

### The good:
- This solution keeps role definition self-contained on the module level, which makes development easier. You just have to register the changes in the authorizer instead of storing them locally.
- Interoperability also becomes simpler, since when working on another module you'd just be referencing the interface of the Module Type you want to integrate, and not digging around in the authorizer or moduleManager to get any deployment address of other modules.

### The bad:
- Each Module Interface Type is forced to share roles with all others using that interface. Can also be seen as a feature, though: you could set up roles that affect all LogicModules, all PaymentClients (but still set up specific roles for IStreamingPaymentClients). But if you want to have two completely independent NFTGatedStreamingMilestoneModules inside the same proposal, it's an issue.

### The ugly:
- Enums aren't part of the contract interface. This isn't a problem functionally, but it would be more elegant to just do something like isAuthorized(ILogicModule.Roles_enum role, address who). We'd just use the uint8 corresponding to that Enum value, but it also kind of means there isn't a "source of truth" in the interface, and opens up the issue of Modules calling role numbers that don't exist, which the authorizer can't really check (although if a role is uninitialized it defaults to false, so the harm is limited). One way to circumvent this would be to store the total amount of roles in the module as a constant and use it as reference. This is ugly and unnecessary, but it would make that information more explicit so maybe it's worth it? 
- Or of course we can always say "fuck it" and store the roles as a constant string array, and just use that to generate the identifiers. That can be part of the interface without an issue. Seems hacky though.


## Changes to existing code that would need to be done:
- Make the base Module inherit ERC165. Not a big deal and probably a good idea anyway
- modify *isAuthorized* to include bytes32 role by default. Also not a big deal and kind of expected.
- Define OWNER and MANAGER in the proposal and store them in the authorizer on setup. This would leave the whole "Ownable" inheritance branch kind of hanging, so maybe we'd need to remove that too? Feels a bit scary.


So, I hope I made sense! Do you guys see any major issues? What are your thoughts?

**Comment by FHieser** [comment]
"But if you want to have two completely independent NFTGatedStreamingMilestoneModules inside the same proposal, it's an issue." -> That really might be a problem.
Could we solve this by adding a variable unique to the Module into the role itself? An encoding of the address for example?
For example keccak256(abi.encodepacked( address(this),RoleName))

**Comment by FHieser** [comment]
"Enums aren't part of the contract interface."
Cant we just expand on the existing code? I dont think we dont have to restrict ourself to the existing code no?
My thoughts on the implementation was that we modify the hasRole function to take a enum too.
So hasRole(Role, infoEnum) would as soon as it gets into the correct function split the controlflow with the help of the enum away from the original OpenZepplin Implementation into our own

That way we can keep practically everything form openzepplin and just have to expand our own functionality onto it

**Comment by 0xNuggan** [comment]
Thanks for the comments Felix! Regarding the issues you mentioned:
- "Enums aren't part of the contract interface": Sorry I should've been more clear. What I meant was that [enums don't get stored in the ABI](https://docs.soliditylang.org/en/latest/abi-spec.html#mapping-solidity-to-abi-types). Instead they get converted to an uint8 representing the position inside the enum. So the authorizer would just get a number and has no way to check for validity without importing the full contract itself. That's why I mentioned just using strings instead as a replacement solution, or storing a `const numOfRoles` in the interface and use it for basic validation (and rely on "bool mappings default to false" for the rest). The usual solution for this (create a Types.sol library declaring the enums and share it around) doesn't work in this case since we'll have lots of modules with their different roles, and which ones will be used where won't be clear until deployment.
- Hashing the address into the roleID would solve this, yes. It would also automatically enforce that a module can only modify it's own roles. But if a Module wants to read another module's roles it forces them to "search" for that address to generate the ID. For mandatory modules it's easy (you can just ask the proposal) but for other logic Modules you'll probably have to set it up manually.  Not *that much* of a deal, I just liked the idea of saying "Hey, my module should have the same access control as the NFTMinter module. I`ll just import the interface and now I can rely on the authorizer without doing anything else"

**Comment by 0xNuggan** [comment]
Also another issue with using the address instead of the interface for the id has is that it ties the roles to that specific deployment instance. Let's imagine we want to swap out one PaymentProcessor for another. It would make sense to keep the same roles in place, and not have to reauthorize every single user.

**Comment by FHieser** [comment]
In regards of the enum thing:
I dont mean for them to be part of the data storage but to be part of the controlflow so to say.
you dont have to safe them you can just use them as a PArameter in the justRole() modifier, that we will use at some point

**Comment by FHieser** [comment]
hashing addresses:
You wouldnt necessarily need to create "hashed" Roles. If you create a role that you are certain you want to be global, just dont hash them. Then everybody can use them.
I think in general it would be best to keep every role global except the ones that have to be Address specific

**Comment by FHieser** [comment]
"Also another issue with using the address instead of the interface for the id has is that it ties the roles to that specific deployment instance. Let's imagine we want to swap out one PaymentProcessor for another. It would make sense to keep the same roles in place, and not have to reauthorize every single user."
With global roles this wouldnt be an issue, for "Hashed" Roles that would be an issue I agree.
Question here would be How often are Modules swapped that contain Hashed Roles? How many addresses would be in these Hashed Roles anyway?

**Comment by 0xNuggan** [comment]
Thanks for all the feedback! I've ended up going somewhat with a middle road:
-Role ID hashes are generated with the address of the module they correspond to. In addition to that, the RoleAuthorizer Module has two basic roles (Owner and Manager)which are generated with the proposal's address and easily queryable. Owners have a way to create more global roles.
- By default, Modules delegate their authorization to the Roles from the Authorizer. They can however toggle self-management, in which case they'll be using their own roles instead.
-There is an admin role that can modify the roles from a module. It is empty by default, but owners can add addresses. Modules can burn this admin role on a per-role basis, in case they need to specifically prohibit owners from modifying certain roles.
- Modules can freely grant or revoke authorization on their own roles.

I've openeded a draft PR with this if anybody wants to take a look. Some tests are missing, so there may be smaller changes, but the general structure should be solid.


ALSO (although I'll probably open a separate issue for this) : While working with the whole owner/manager stuff, I noticed that we aren't actually using the Manager role for anything outside of the milestoneManager and recurringPayment modules. We declare a lot of onlyAuthorizedOrManager() modifiers and never employ them :laughing:  :
- The Proposal never uses the modifier ever. The only mention of manager is the manager() func, that returns the Ownable owner() value. (Incidentally, we don't use onlyOwner anywhere in the proposal either).
- The Base Module only uses it for pause() and unpause()... which amount to nothing since not a single Module uses whenPaused and whenUnPaused (We could remove the whole dependency I think… If a specific module wants to be pausable they can reimport)

So: I think we could remove the onlyAuthorizerOrManager from the core contracts and with it cull the Pausable and Ownable dependencies. This way, we could have a basic proposal with an isAuthorized function that does the same as onlyOwner(), and if Modules need more roles they can enforce different IAuthorizer modules on initialization by specifying ERC165.
