### ISSUE TITLE
Code review results - BountyManager

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#315]
Another picture dump for now - for the next one they'll probably do the PR directly in this repo so everybody can comment

![Screenshot from 2023-08-08 05-55-33](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/68b367c5-49f3-4afc-b6a8-1fcbae10ae37)
![Screenshot from 2023-08-08 05-55-42](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/acb36b03-5a2f-4eaf-a1a5-8506073dad74)
![Screenshot from 2023-08-08 05-55-49](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/58e3d784-0a40-4c53-accb-5b7e7b05b133)
![Screenshot from 2023-08-08 05-55-53](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/437f37a5-8691-4e40-b72e-61f959aba049)
![Screenshot from 2023-08-08 05-55-58](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/51cc8a5e-cc3f-45af-941b-04b1c06bd850)
![Screenshot from 2023-08-08 05-56-02](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/44bd1eff-81ef-42f1-a178-f8e5fa9e60c8)
![Screenshot from 2023-08-08 05-56-05](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/22df73cf-4192-43fc-93ff-02fd7903a4af)
![Screenshot from 2023-08-08 05-56-08](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/7632a367-9d7e-428c-9dda-768e3f46d3c4)
![Screenshot from 2023-08-08 05-56-14](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/9b4853ea-1ac7-472b-a0d8-e1160efebab7)
![Screenshot from 2023-08-08 05-56-22](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/ea7bec57-6af2-40b1-b4ed-9d179ca8e221)
![Screenshot from 2023-08-08 05-56-26](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/b8d561f2-18d6-4eae-a794-82dbb3df4d96)
![Screenshot from 2023-08-08 05-56-30](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/f3b4144b-3d8f-4db5-9429-ea0b98c95016)
![Screenshot from 2023-08-08 05-56-35](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/63a2f00f-d438-4125-89d6-9b95be92d5cd)
![Screenshot from 2023-08-08 05-56-43](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/ca4e9e33-14d7-4456-9b69-7e024b0cf8b8)
![Screenshot from 2023-08-08 05-58-21](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/7627204a-6782-4948-b9ff-e672467254df)
![Screenshot from 2023-08-08 05-58-25](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/d728b3d5-4d5c-4c33-b3d4-9a0e39e91b6a)
![Screenshot from 2023-08-08 05-58-31](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/031a4cf6-fa20-49af-8dec-28e7da3cca4e)
![Screenshot from 2023-08-08 05-58-37](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/1f65c078-53a5-4600-b55f-a5f74e3c5f4a)

**Comment by FHieser** [comment]
1. validContributorsForBounty function positioning
2. init2 critique
3. Linked list critique
4. Linked list critique
5. EnumerableSet contributorAddressToClaimIds
6. ClaimContributor Role
7. add notClaimed to Update function
8. add notClaimed to update Function
9. verifyClaim frontrun
10. addPaymentOrders not properly used
11. PaymentClient wet code
12. event indexed?
13. Parameter upper case
14. burnAdmin Role
15. Refactoring comment "Why later?"
16. address check not sufficient
17. ensureTokenBalance faulty
18. Refactoring comment "Why postpone refactors?"

**Comment by FHieser** [comment]
1. This is essentially a modifier, but I had to convert it into a function because of stackTooDeep Error. I would just keep it in that position
2. This will be tackled in a separate issue #319 
3. Design Decision
4. Design Decision
5. You are technically correct here. This could be done on the front end, but as we currently dont have a frontend team to rely on implementing this feature we have to realize it in some way, because it makes sense to have this feature from a UX perspective.
6. Yeah your probably right here. It makes sense to restrict at least the change of possible Contributors to be restricted to the ClaimAdmins too.
7. Agreed
8. Agreed
9. Agreed
10. Agreed
11. This is tackled in #261
12. For some reason I assumed that indexed parameters are cheaper gas wise. I will change that
13. Agreed
14. @0xNuggan any opinion on this?
15. This is already tackled in the following PR #313
16. correct in that we probably always could test more in address checks, but at some point it just defeats the purpose. Will keep it as is.
17. Correct. We will tackle this in another issue
18. Refactors are already on the way
