### ISSUE TITLE
Code review results - Orchestrator

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#317]
Another picture dump for now - for the next one they'll probably do the PR directly in this repo so everybody can comment

![Screenshot from 2023-08-08 05-53-08](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/71cf8a66-2af0-492f-a979-d7fa1c841e56)
![Screenshot from 2023-08-08 05-53-13](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/93c39970-0c30-405d-945b-78ee77346544)
![Screenshot from 2023-08-08 05-53-22](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/8fb632d4-361f-4eb1-a80a-b7576b71df1c)
![Screenshot from 2023-08-08 05-53-32](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/ba504575-82c7-4fe4-92db-7de1d01b0f7c)
![Screenshot from 2023-08-08 05-53-41](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/85ca3e24-8344-4c4b-983e-d8f9d0043af2)
![Screenshot from 2023-08-08 05-53-50](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/f2b14b85-14ea-4b4d-b798-140e24bf6496)
![Screenshot from 2023-08-08 05-59-10](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/10971cee-e7e9-4273-af2a-a2ea6b6ff375)
![Screenshot from 2023-08-08 05-59-14](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/f1eeb98e-cff0-42ad-9ac5-fb54fedf7270)

**Comment by saxenism** [comment]
Ok, so here is the reasoning for adding the `verifyAddresIsXYZModule` functions in the Orchestrator contract:

The ideal work-flow involving these functions are:
1. A new module needs to be added to the inverter work-flow
2. That module has a cross-dependency of some other module (ie it requires late dependency injection)
3. So, the logic of initializing this function would require some additional logic referring to the other contracts in the function `init2`
4. Now, the process of using another module for the initialization of the new module would involve: finding the dependency module address and then verifying whether the address is indeed of the type of module that we require.
5. So, for the finding part we use the function: `findModuleAddressInProposal`
6. And, for the verifying part we use the functions of type: `verifyAddresIsXYZModule`

Now, why did we select only a few modules for verification, it's because we thought about *the most important* module that might be needed for late dependency injection and included them. The modules that we thought were not absolutely critical, were left out.

Ok, so with the auditors' comments in mind, we have the following points up for discussion:
1. Scrape the `verifyAddresIsXYZModule` functions completely as they are not really essential to the functioning of the protocol and have been termed as a **bad idea architecturally** by them.
2. Create another (upgradable) helper contract for verification.
3. Keep this idea of verification, but replace the `verifyAddresIsXYZModule` functions with EIP-165.

@FHieser @0xNuggan @marvinkruse @SchneiderNejc please let me know your thoughts on this.

**Comment by saxenism** [comment]
Agree with the assessment about multiple modules being able to use the same name.

Opened PR #327 to address this.

**Comment by saxenism** [comment]
The last comment about scraping the function `findModuleAddressInOrchestrator` does not make sense to me. Maybe we could discuss this to understand what the auditors are trying to say?

In my opinion at least, when external developers create new modules that have cross-dependencies, the `findModuleAddressInOrchestrator` function would help them out quite a bit in their function initialization (via `init2`)
