### ISSUE TITLE
Security Review #350: ERC20PaymentClient findings

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#366]
### This issue is linked to
- PR #350
### Explanation
- Tokens may get stuck in the contract.

### Category:
- Critical

### Link to review comments
*Should be marked as done*
- [x] https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1355193745
- [x] https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1359788798
- [x] https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1355196779

**Comment by Zitzak** [comment]
Added one more review comment to this list, because it also within the ERC20PaymentClient. jfyi @0xNuggan

**Comment by FHieser** [comment]
The first comment was:
you removed the part where ensureTokenBalance only adds additional tokens (i.e. adds amount- balance tokens).
That is in itself not wrong and probably an improvement.

But the effect is that if the contract contains tokens already that are not claimed, they may remain stuck in the contract. This holds for tokens that are sent directly to the contract, for tokens that are somehow "unclaimable" or are never claimed by the rightful owner, and it may also hold for tokens from canceled orders in a paymentprocessor (such as StreamingPaymentProcessor)

**Comment by FHieser** [comment]
My Answer:
Yeah your right.
The initial purpose of the amount - balance was to prevent that.
The problem here is with the creation of a "vent" to drain funds we come into the risk of not guaranteeing that payments can go out.
In case of -> Are never claimed by the rightful owner:
This is in my opinion the correct behavior. Even if the address doesnt claim the funds it still has a right to do so.
In case of -> tokens that are sent directly to the contract:
Totally agree.

In general the problem with these tokens that lay around and do nothing is, that they are perceived as "useless".
Maybe a mechanism to put them to use (staking or other) may be a way to go here.
I will talk to the others about this.

Any opinion on this @marvinkruse @0xNuggan  @Zitzak ?
